### ISSUE TITLE
건의사항: 안드로이드 써드파티 앱 관련

### ISSUE THREAD

**Issue by qkdxorjs1002** [anissia-net/document#1]
애니시아 편성표 잘 쓰고 있습니다. 이제 거의 10년 가까이 사용하고 있네요.

이번에 API 새로 개편되면서 안드로이드용 앱을 개발하게 되었는데,
애니시아 홈페이지에 써드파티 앱으로 등록해주십사 해서 이슈를 작성합니다.

[앱 Repo 링크](https://github.com/qkdxorjs1002/AniSched-Android)

아직 개발 단계에 있지만 핵심 기능은 구현이 되어있습니다.
배포는 일단 Github를 통해 할 계획이고 추후에 어느정도 완성도가 만족되었을 때 플레이 스토어에 등록하려고 합니다.

**Comment by marker-seoul** [comment]
금일 개인적으로 몸이 아파서 반차쓰고 쉬고있다가 이제봤습니다.

https://anissia.net/schedule
위에 추가해 두었습니다.

나중에 완성하셔서 안드로이드 마켓에 업로드하시면 다시 알려주세요.
