### ISSUE TITLE
업데이트: 안드로이드 써드파이 앱 관련 건의

### ISSUE THREAD

**Issue by qkdxorjs1002** [anissia-net/document#2]
안녕하세요, #1 해당 이슈로 건의 드렸었는데 업데이트가 있어 남깁니다.

플레이 스토어에 등록하여 검토 진행 중 입니다. [플레이스토어 링크](https://play.google.com/store/apps/details?id=com.novang.anisched)

건강 유의하시고 항상 감사드립니다.

**Comment by marker-seoul** [comment]
@qkdxorjs1002 
안녕하세요.
구글 플레이에 출시되고 나면 댓글 한번 더 부탁드립니다.

**Comment by qkdxorjs1002** [comment]
@ac-saro 
활성화 되었습니다. 생각보다 오래걸리는군요..

**Comment by marker-seoul** [comment]
@qkdxorjs1002 
지금 자막제작자 권한 제작중인데요.
내일쯤 적용할 것 같으니 내일 업로드할대 같이 업로드하겠습니다.
